name: SwiftFormat Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  swiftformat:
    name: Check code formatting with SwiftFormat
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install SwiftFormat
        run: |
          git clone --branch 0.62.1 --depth 1 https://github.com/nicklockwood/SwiftFormat.git
          cd SwiftFormat
          swift build -c release
          sudo cp .build/release/swiftformat /usr/local/bin/swiftformat
          swiftformat --version
      - name: Check Formatting
        run: swiftformat --lint .
